// ──────────────────────────────────────────────
// Demo mode — mock AI responses when OpenAI key is not configured
// ──────────────────────────────────────────────

import type { ProcessTaskResult } from "./openai";

/**
 * Check if we're running in demo mode (no real OpenAI API key).
 * Demo mode activates when OPENAI_API_KEY is missing or placeholder,
 * UNLESS DEMO_MODE is explicitly set to "false" (forces real OpenAI path).
 *
 * Priority:
 *  1. DEMO_MODE="false" → always NOT demo mode (forces OpenAI path, errors if no key)
 *  2. DEMO_MODE="true"  → always demo mode (even if key is present)
 *  3. Default: demo mode if API key is missing, empty, or "***"
 */
export function isDemoMode(): boolean {
  if (process.env.DEMO_MODE === "false") return false;
  if (process.env.DEMO_MODE === "true") return true;
  const apiKey = process.env.OPENAI_API_KEY;
  return !apiKey || apiKey === "***" || apiKey === "";
}

/**
 * Generate a plausible mock AI response based on the task title and description.
 * These look realistic enough for demos but are clearly synthetic.
 */
function generateMockResponse(title: string, description: string): string {
  const lowerTitle = title.toLowerCase();
  const lowerDesc = description.toLowerCase();

  // Research tasks
  if (
    lowerTitle.includes("research") ||
    lowerTitle.includes("find") ||
    lowerTitle.includes("compare") ||
    lowerDesc.includes("research") ||
    lowerDesc.includes("findings")
  ) {
    return `## Research Results: ${title}\n\nBased on my analysis, here are the key findings:\n\n### Key Insights\n\n- **Market Overview**: The landscape is evolving rapidly with several notable trends emerging in the past quarter\n- **Top Competitors**: Three main players dominate the space, each with distinct strengths and weaknesses\n- **Pricing Range**: Solutions in this category typically range from $20-150/month depending on feature set\n- **User Sentiment**: Reviews indicate strong satisfaction with ease-of-use but concerns about scalability\n\n### Recommendations\n\n1. Start with a free trial of the top-rated option before committing\n2. Consider the long-term roadmap — today's best choice may not be optimal in 12 months\n3. Look for solutions with strong API support for future automation needs\n\n### Sources\n- Industry reports and review aggregators\n- Community forums and social sentiment analysis\n- Direct competitor website analysis\n\n---\n*Note: This is a demo response generated by TaskDrip in demo mode. With a configured OpenAI API key, responses are generated by GPT-4o-mini with real-time AI analysis.*`;
  }

  // Writing tasks
  if (
    lowerTitle.includes("write") ||
    lowerTitle.includes("draft") ||
    lowerTitle.includes("email") ||
    lowerTitle.includes("blog") ||
    lowerTitle.includes("letter") ||
    lowerDesc.includes("write") ||
    lowerDesc.includes("draft")
  ) {
    return `## Draft: ${title}\n\nI've completed a draft based on your requirements. Here's the polished result:\n\n---\n\nThank you for your recent inquiry. I wanted to follow up and share some important updates regarding our progress.\n\nOver the past quarter, we've made significant strides in several key areas. Our team has focused on delivering value while maintaining the quality standards our stakeholders expect.\n\n**Key highlights:**\n\n- Completed the initial phase ahead of schedule\n- Received positive feedback from early users and partners\n- Identified two promising opportunities for expansion\n\nNext steps include refining our approach based on the feedback received and preparing for the upcoming milestone review. I'm confident this direction will yield strong results.\n\nPlease don't hesitate to reach out if you have any questions or would like to discuss further.\n\n---\n\n*This draft can be further refined — let me know the specific tone or style adjustments you'd like.*\n\n---\n*Note: This is a demo response generated by TaskDrip in demo mode. With a configured OpenAI API key, responses are generated by GPT-4o-mini with AI-powered writing assistance.*`;
  }

  // Analysis tasks
  if (
    lowerTitle.includes("analyz") ||
    lowerTitle.includes("review") ||
    lowerTitle.includes("summar") ||
    lowerTitle.includes("evaluat") ||
    lowerDesc.includes("analyz") ||
    lowerDesc.includes("summar")
  ) {
    return `## Analysis: ${title}\n\n### Executive Summary\n\nThe analysis reveals several important patterns and actionable insights worth considering.\n\n### Findings\n\n**Strengths:**\n- Strong fundamentals with consistent performance metrics\n- Positive trajectory over the evaluation period\n- Clear alignment between stated goals and observed outcomes\n\n**Areas for Improvement:**\n- Some inefficiencies in the current workflow that could be streamlined\n- Opportunity to leverage automation for repetitive tasks\n- Communication gaps between teams that impact velocity\n\n**Risks:**\n- External factors could shift the competitive landscape\n- Resource constraints may limit near-term execution speed\n\n### Recommendations\n\n1. **Immediate**: Address the top workflow bottleneck identified in Section 2\n2. **Short-term**: Implement the suggested automation for Report Generation\n3. **Medium-term**: Revisit the resource allocation model ahead of Q3 planning\n\n### Conclusion\n\nOverall, the picture is positive with clear opportunities for optimization. The recommended actions should yield measurable improvements within 4-6 weeks.\n\n---\n*Note: This is a demo response generated by TaskDrip in demo mode. With a configured OpenAI API key, responses are generated by GPT-4o-mini with deeper AI analysis.*`;
  }

  // Default / generic task
  return `## Task Complete: ${title}\n\nI've completed the task you described. Here's a summary of what was done:\n\n### What I Did\n\n1. Reviewed the task requirements: "${title}"\n2. Analyzed the details provided in the description\n3. Generated a structured response based on the task type\n4. Formatted the output for clarity and actionability\n\n### Result\n\nThe task has been processed successfully. The key outputs are:\n\n- A structured analysis of the provided information\n- Actionable next steps based on the task requirements\n- Relevant context and considerations for follow-up\n\n### Next Steps\n\n- Review this output and let me know if you'd like any adjustments\n- You can create a follow-up task to drill deeper into any specific area\n- Consider sharing results with relevant team members\n\n---\n*Note: This is a demo response generated by TaskDrip in demo mode. With a configured OpenAI API key, responses are generated by GPT-4o-mini with real AI-powered task completion.*`;
}

/**
 * Process a task using mock/demo AI instead of OpenAI.
 * Includes a small artificial delay to simulate processing time.
 */
export async function processTaskWithDemoAI(
  title: string,
  description: string
): Promise<ProcessTaskResult> {
  // Simulate processing delay (1-3 seconds)
  const delay = 1000 + Math.random() * 2000;
  await new Promise((resolve) => setTimeout(resolve, delay));

  const resultText = generateMockResponse(title, description);

  return { success: true, resultText };
}